org.gradle.jvmargs=-Xmx3G

minecraft_version=1.21.1

archives_base_name=Enhanced-Celestials
mod_version=6.0.2.6
maven_group=dev.corgitaco.enhancedcelestials

fabric_loader_version=0.17.0
fabric_api_version=0.116.4

forge_version=52.1.3

neoforge_version=21.1.197

parchment=2024.07.28

# Upload Settings
curseforge_id=438447
modrinth_id=2rL16t1O

# Mod options
mod_name=Enhanced_Celestials
mod_author=Corgi Taco
mod_id=enhancedcelestials

# CorgiLib
corgilib_version=5.0.0.9
data_anchor_version=2.0.0.13
timecore_version=1.0.1

# Other Mods
sodium_version = mc1.21.1-0.6.1-fabric
iris_version = 1.8.1+1.21.1-fabric

loom.ignoreDependencyLoomVersionValidation=true

# Gradle
org.gradle.daemon=false
